apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins-ns
spec:
  volumeMode: Filesystem
  storageClassName: jenkins-sg
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
